[models.qwen3_local]
routing = ["sglang"] # List of allowed providers

# ---- Provider block ---------------------------------------------------------
[models.qwen3_local.providers.sglang]
type = "openai"                                   # openai provider as sglang native api has no tool call support
api_base = "http://host.docker.internal:30000/v1"
api_key_location = "none"                         # SGLang default = no auth
model_name = "qwen3"

###############################################################################
# 2)  Functions & variants
###############################################################################
[functions.qwen]
type = "chat"

[functions.qwen.variants.default]
type = "chat_completion"
model = "qwen3_local"    # Points back to the model block
